### ISSUE TITLE
S3 Client side encryption docs reference outdated info.

### ISSUE THREAD

**Issue by MariusVolkhart** [awsdocs/amazon-s3-userguide#15]
The docs at https://github.com/awsdocs/amazon-s3-userguide/blob/main/doc_source/UsingClientSideEncryption.md link to https://aws.amazon.com/articles/client-side-data-encryption-with-the-aws-sdk-for-java-and-amazon-s3/

That article is from 2011. The APIs it uses are all deprecated. The information however, is relevant since new APIs for similar functionality exist.

**Comment by DBirtolo-AMZ** [comment]
Thank you for bringing this to our attention! Since the information in the article is still relevant, we think it would be best to leave the link in so that customers can get the information that is useful. We don't have the ability to update the article with current APIs, so we can only either remove the link or leave it. If the article wasn't still relevant, we could eliminate the link completely.
