### ISSUE TITLE
When to use "s3:x-amz-server-side-encryption" policy?

### ISSUE THREAD

**Issue by epomatti** [awsdocs/amazon-s3-userguide#72]
I'm trying to understand the use case for this policy directive `"s3:x-amz-server-side-encryption"` as demonstrated in this [server side encryption][1] page.

If one can enable transparent default encryption for the whole bucket, why use this policy?

![image](https://user-images.githubusercontent.com/6530769/180648279-ccc82d46-acb1-4bc3-a540-2c93380f757d.png)

Is it to be used where buckets do not have encryption enabled, and therefore enforcing encryption on specific conditions, like specific prefixes, extensions, etc? In this case some files are encryption, some are not.

When use one, and not the other?

```json
{
  "Version": "2012-10-17",
  "Id": "PutObjectPolicy",
  "Statement": [
    {
      "Sid": "DenyIncorrectEncryptionHeader",
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::awsexamplebucket1/*",
      "Condition": {
        "StringNotEquals": {
          "s3:x-amz-server-side-encryption": "AES256"
        }
      }
    }
  ]
}
```

It enforces the client to select the encryption algorithm:

```sh
aws s3api put-object --body somefile.png --bucket mybucket --server-side-encryption 'AES256'
```

This is the help text form the AWS CLI for the `--server-side-encryption` option:

> The server-side encryption algorithm used when storing this object in Amazon S3 (for example, AES256, aws:kms).

[1]: https://github.com/awsdocs/amazon-s3-userguide/blob/main/doc_source/UsingServerSideEncryption.md

**Comment by aws-alan** [comment]
Hello,

This policy does serve a similar function as setting default server-side encryption on a bucket.
 
This shows this could alternatively been done through bucket policies. As you've pointed out a customer might prefer this because they can add specific conditions such as requiring encryption only if an object begins with a certain prefix.

Someone may also want to use both a bucket setting and a policy. For example, if they only wanted to use SSE-S3 and didn’t want someone to be able to specify AWS KMS encryption in PutObject request (or the other way around).
